name: Lint

on: [pull_request]

permissions:
  contents: read

jobs:
  check-gems:
    name: Check gem files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Not needed with a .ruby-version file
          bundler: 'default'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec .check.rb
