name: Lint

on: [pull_request]

permissions:
  contents: read

jobs:
  check-gems:
    name: Check gem files
    runs-on: ubuntu-latest
    env:
      BASE_REF: ${{ case(github.event_name == 'pull_request', github.event.pull_request.base.sha,
                         github.event.before == '0000000000000000000000000000000000000000', 'master',
                         github.event.before) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@a0102e0972be65f351c307e2d64b9314a57c8073 # v1.324.0
        with:
          ruby-version: '3.4' # Not needed with a .ruby-version file
          bundler: 'default'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Fetch base revision
        run: |
          git fetch --depth 1 origin "${BASE_REF}"
          if [ "${BASE_REF}" = "master" ]
          then
            git branch master origin/master
          fi
      - name: Validation
        run: bundle exec .check.rb --gitrepo --gitdiff "${BASE_REF}"
