name: Lint

on: [pull_request]

permissions:
  contents: read

jobs:
  check-gems:
    name: Check gem files
    runs-on: ubuntu-latest
    env:
      BASE_REF: ${{ case(github.event_name == 'pull_request', github.event.pull_request.base.sha,
                         github.event.before == '0000000000000000000000000000000000000000', 'master',
                         github.event.before) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
        with:
          ruby-version: '3.4' # Not needed with a .ruby-version file
          bundler: 'default'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Fetch base revision
        run: |
          git fetch --depth 1 origin "${BASE_REF}"
          if [ "${BASE_REF}" = "master" ]
          then
            git branch master origin/master
          fi
      - name: Validation
        run: bundle exec .check.rb --gitrepo --gitdiff "${BASE_REF}"
